references:
  commands:
    setup-docker: &setup-docker
      docker:
        - image: kurosame/circleci-node

version: 2
jobs:
  test:
    <<: *setup-docker
    steps:
      - checkout
      - restore_cache:
          name: Download and cache dependencies
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run:
          name: Install
          command: yarn install
      - run:
          name: Test for CI
          command: yarn test:ci
      - save_cache:
          name: Cache dependencies
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - store_artifacts:
          path: ./test/unit/coverage
  e2e:
    <<: *setup-docker
    steps:
      - checkout
      - restore_cache:
          name: Download and cache dependencies
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run:
          name: Install
          command: yarn install
      - run:
          name: E2E Test for CI
          command: yarn e2e:ci
      - save_cache:
          name: Cache dependencies
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - store_artifacts:
          path: ./test/e2e/specs/__screenshots__
  outdated:
    - run:
        name: Outdated
        command: curl -X POST $SLACK_WEB_HOOK_URL -d "text=${ yarn outdated }"

workflows:
  version: 2
  test:
    jobs:
      - test
      - e2e
  nightly:
    triggers:
      - schedule:
          cron: '2/4/6/8/10/12/14/16/18/20/22/24/26/28/30/32/34/36/38/40/42/44/46/48/50/52/54/56/58 * * * *'
          filters:
            branches:
              only:
                - master
    jobs:
      - outdated
