references:
  commands:
    setup-docker: &setup-docker
      docker:
        - image: kurosame/node
      working_directory: ~/vuejs-boilerplate

version: 2
jobs:
  build:
    <<: *setup-docker
    steps:
      - checkout
      - restore_cache:
          name: Download and cache dependencies
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run:
          name: Install
          command: yarn install
      - run:
          name: Build for vendor
          command: yarn build:vendor
      - run:
          name: Build for production
          command: yarn build:production
      - save_cache:
          name: Cache dependencies
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
  test:
    <<: *setup-docker
    steps:
      - checkout
      - restore_cache:
          name: Download and cache dependencies
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run:
          name: Install
          command: yarn install
      - run:
          name: Build for vendor
          command: yarn build:vendor
      - run:
          name: Test for CI
          command: yarn test:ci
      - save_cache:
          name: Cache dependencies
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
  e2e:
    <<: *setup-docker
    steps:
      - checkout
      - restore_cache:
          name: Download and cache dependencies
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run:
          name: Install
          command: yarn install
          working_directory: 'vuejs-boilerplate'
      - run:
          name: Build for vendor
          command: yarn build:vendor
          working_directory: 'vuejs-boilerplate'
      - run:
          name: E2E Test for CI
          command: yarn e2e:ci
          working_directory: 'vuejs-boilerplate'
      - save_cache:
          name: Cache dependencies
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

workflows:
  version: 2
  test:
    jobs:
      - test
      - e2e
